# Generated by Django 5.1.1 on 2025-05-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ad_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeproposal',
            name='comment',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
